# Generated by Django 2.2 on 2019-04-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('head', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('realname', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_broker', models.BooleanField()),
            ],
            options={
                'db_table': 'camel_user',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('image_url', models.CharField(default='', max_length=120)),
                ('houseType', models.CharField(default='', max_length=40)),
                ('contractTag', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField()),
                ('endorsementFee', models.IntegerField()),
                ('homeAddress', models.CharField(default='', max_length=120)),
                ('roomSize', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
