# Generated by Django 2.2 on 2019-04-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camel', '0002_auto_20190417_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
