# Generated by Django 2.2 on 2019-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camel', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
