# Generated by Django 2.2 on 2019-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camel', '0004_auto_20190417_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
