# Generated by Django 2.1.7 on 2019-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camel', '0004_auto_20190410_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('image_url', models.CharField(default='', max_length=120)),
                ('houseType', models.CharField(default='', max_length=40)),
                ('contractTag', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField()),
                ('endorsementFee', models.IntegerField()),
                ('homeAddress', models.CharField(default='', max_length=120)),
                ('roomSize', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
